### ISSUE TITLE
F chords are missing from data file

### ISSUE THREAD

**Issue by Shnatsel** [robertpearce/chord-finder#1]
Chords in the .csv go A-B-C-D-E-G, missing F entirely. I'd appreciate if you could correct that. I'm trying to reuse the fret parsing module in my own project and this is a massive blocker even for personal use.

**Comment by robertpearce** [comment]
I'll take a look. I think i missed them originally just because i don't know any F chords ;-( I'll google some and add them in.

**Comment by robertpearce** [comment]
try that. I'll see if i can dig up any other useful F chords but i think it'll cover most cases.

**Comment by Shnatsel** [comment]
Seems to work as expected. Thanks!
