### ISSUE TITLE
Not actually an issue, just question about GPL

### ISSUE THREAD

**Issue by Shnatsel** [robertpearce/chord-finder#4]
Hey Robert! I've failed to reach you by email, so I'm posting here instead.

I've written a small script to convert guitar chords in arpeggios to individual notes. It uses your ChordData.csv and I might have lifted some code too, but I can't see any obvious copypasta and I started it a long time ago, so I can't remember if I actually used your code or not.

I was going to put it under something more permissive than GPL since it's so simple, but since it might be a derivative of your GPL work I thought I'd ask if you want it GPL'd. Here's the script: http://pastebin.com/mFxxyXyZ

Thanks again for creating chord-finder!

**Comment by robertpearce** [comment]
no problem at all. I never actually thought anyone would use it, let alone use the code :)

If you want i can roll this back into the main codebase as a feature and provide arpeggio functionality via a button or something similar ?.

**Comment by Shnatsel** [comment]
Note display could be useful, after writing my script I've noticed 8notes already does that: http://www.8notes.com/guitar_chord_chart/c.asp Their presentation is probably a good idea and worth copying.

That said, running the full chord-finder is a pain due to wx dependency and hardcoded fonts. It would be nice to see my code reused, but I'd prefer to keep my script separate. It's just a tiny helper tool and I'd prefer to keep it as small and devoid of dependencies as possible.

**Comment by robertpearce** [comment]
yeah. i can certainly make the fonts not hard-coded - but there;s no way around wxpython.

I'll close this issue for now. but yeah, feel free to do whatever you want with the code, up to and including selling it for gingerbread men cookies ;-)
